namespace Cuvara.UIToolkit.Codegen
{
    using System.IO;
    using System.Text;

    /// <summary>
    /// File-level orchestration over <see cref="UxmlBindingGenerator"/>: paths, class
    /// names, namespace resolution, byte comparison, writing. Shared verbatim by the
    /// Editor integration (menu + postprocessor) and the drift-check CLI, so both always
    /// produce the same bytes for the same UXML.
    /// </summary>
    /// <remarks>
    /// <para><b>This file must stay Unity-free</b> — see
    /// <see cref="UxmlBindingGenerator"/>. System.IO only; anything touching
    /// <c>AssetDatabase</c> belongs in the Editor layer.</para>
    ///
    /// <para><b>The write is content-gated.</b> <see cref="RegenerateIfChanged"/> compares
    /// the freshly generated bytes with the file on disk and does NOT write when they are
    /// identical. In the Editor that is what breaks the import loop: writing the
    /// <c>.g.cs</c> triggers an import, and an unconditional write on every UXML import
    /// would re-dirty the project forever. In the CLI the same comparison IS the drift
    /// check.</para>
    ///
    /// <para><b>Encoding is part of the contract:</b> UTF-8 without BOM, <c>\n</c>
    /// newlines. Byte-identical means byte-identical.</para>
    /// </remarks>
    public static class UxmlBindingPipeline
    {
        private static readonly UTF8Encoding Utf8NoBom = new(encoderShouldEmitUTF8Identifier: false);

        /// <summary>Suffix of every generated file: <c>&lt;Name&gt;.uxml.g.cs</c>.</summary>
        public const string GeneratedSuffix = ".uxml.g.cs";

        /// <summary>Name of the sibling folder generated files live in.</summary>
        public const string GeneratedFolderName = "Generated";

        /// <summary><c>&lt;uxml-dir&gt;/Generated/&lt;Name&gt;.uxml.g.cs</c> for a UXML path.</summary>
        public static string GetGeneratedPath(string uxmlPath)
        {
            var directory = Path.GetDirectoryName(uxmlPath) ?? string.Empty;
            var name = Path.GetFileNameWithoutExtension(uxmlPath);
            return Path.Combine(directory, GeneratedFolderName, name + GeneratedSuffix);
        }

        /// <summary>Class name for a UXML path: the file name PascalCased, so
        /// <c>ConfirmPopup.uxml</c> and <c>confirm-popup.uxml</c> both yield
        /// <c>ConfirmPopup</c>.</summary>
        public static string GetClassName(string uxmlPath)
        {
            var className = UxmlIdentifier.ToPascalCase(Path.GetFileNameWithoutExtension(uxmlPath));
            if (className.Length == 0)
            {
                throw new UxmlCodegenException($"UXML file name '{Path.GetFileName(uxmlPath)}' yields no C# class name.");
            }

            return className;
        }

        /// <summary>Generates the bindings source for a UXML file, in memory.</summary>
        /// <exception cref="UxmlCodegenException">See <see cref="UxmlBindingGenerator.Generate"/>.</exception>
        public static string GenerateSource(string uxmlPath)
        {
            return UxmlBindingGenerator.Generate(
                File.ReadAllText(uxmlPath),
                Path.GetFileName(uxmlPath),
                GetClassName(uxmlPath),
                UxmlNamespaceResolver.Resolve(uxmlPath));
        }

        /// <summary>The exact bytes <see cref="RegenerateIfChanged"/> would write.</summary>
        public static byte[] GenerateBytes(string uxmlPath)
        {
            return Utf8NoBom.GetBytes(GenerateSource(uxmlPath));
        }

        /// <summary>True when a generated file already exists for this UXML — the opt-in
        /// gate the auto-regen postprocessor checks.</summary>
        public static bool IsEnrolled(string uxmlPath)
        {
            return File.Exists(GetGeneratedPath(uxmlPath));
        }

        /// <summary>
        /// Regenerates <paramref name="uxmlPath"/>'s bindings and writes them, creating
        /// <c>Generated/</c> if needed — UNLESS the existing file is already
        /// byte-identical, in which case nothing is written.
        /// </summary>
        /// <returns>True when the file was written (created or changed), false when it was
        /// already up to date.</returns>
        public static bool RegenerateIfChanged(string uxmlPath)
        {
            var generatedPath = GetGeneratedPath(uxmlPath);
            var freshBytes = GenerateBytes(uxmlPath);

            if (File.Exists(generatedPath) && BytesEqual(File.ReadAllBytes(generatedPath), freshBytes))
            {
                return false;
            }

            Directory.CreateDirectory(Path.GetDirectoryName(generatedPath));
            File.WriteAllBytes(generatedPath, freshBytes);
            return true;
        }

        private static bool BytesEqual(byte[] left, byte[] right)
        {
            if (left.Length != right.Length) return false;
            for (var i = 0; i < left.Length; i++)
            {
                if (left[i] != right[i]) return false;
            }

            return true;
        }
    }
}
