namespace Cuvara.UIToolkit.Codegen
{
    using System.Collections.Generic;
    using System.Text;
    using System.Xml;

    /// <summary>
    /// The pure core of the UXML → typed-view codegen: an XML string in, a generated C#
    /// source string out. No file IO, no Unity.
    /// </summary>
    /// <remarks>
    /// <para><b>This file must stay Unity-free.</b> The whole point of splitting the core
    /// out of the Editor integration is that the drift-check CLI under
    /// <c>Tools~/UxmlCodegenCli/</c> compiles these sources with plain <c>dotnet</c> and
    /// regenerates every enrolled UXML in CI. A <c>UnityEngine</c>/<c>UnityEditor</c>
    /// reference here silently breaks that — System.Xml, System.Text and friends only.</para>
    ///
    /// <para><b>Output is deterministic.</b> Elements are emitted in document order, the
    /// header carries no timestamp, and newlines are always <c>\n</c>, so generating twice
    /// from the same input is byte-identical — which is what makes the CI drift check a
    /// plain byte comparison.</para>
    ///
    /// <para><b>What is emitted.</b> One typed property per named element (PascalCase from
    /// the kebab-case <c>name</c>, type from the tag via a fixed map — unknown or custom
    /// tags fall back to <see cref="FallbackType"/> with a comment naming the original
    /// tag), and one <c>AssignQueries(VisualElement root)</c> method resolving each through
    /// <c>root.Require&lt;T&gt;("name")</c>, so a missing element fails loudly at bind
    /// time instead of null-ing silently. <c>&lt;ui:Template&gt;</c> and
    /// <c>&lt;Style&gt;</c> declarations are skipped: their <c>name</c> is an asset
    /// reference, not an element in the cloned tree.</para>
    /// </remarks>
    public static class UxmlBindingGenerator
    {
        /// <summary>The XML namespace UXML maps Unity's runtime controls into.</summary>
        public const string UnityElementsNamespace = "UnityEngine.UIElements";

        /// <summary>The type an unknown or custom tag falls back to.</summary>
        public const string FallbackType = "VisualElement";

        // Runtime controls of UnityEngine.UIElements that a query can meaningfully return
        // typed. Tags absent here (and every custom tag) fall back to VisualElement — the
        // query still resolves, the property is just less specific.
        private static readonly HashSet<string> KnownElementTypes = new()
        {
            "VisualElement", "Label", "Button", "Toggle", "TextField", "Slider",
            "SliderInt", "MinMaxSlider", "ScrollView", "ListView", "TreeView", "Foldout",
            "Image", "DropdownField", "EnumField", "RadioButton", "RadioButtonGroup",
            "ProgressBar", "GroupBox", "RepeatButton", "Scroller", "TwoPaneSplitView",
            "TemplateContainer", "MultiColumnListView", "MultiColumnTreeView", "TabView",
            "Tab", "ToggleButtonGroup",
        };

        /// <summary>
        /// Generates the bindings class for one UXML document.
        /// </summary>
        /// <param name="uxmlText">The UXML file content, parsed as plain XML.</param>
        /// <param name="sourceFileName">File name (no directory) recorded in the generated
        /// header, e.g. <c>ConfirmPopup.uxml</c>. Name only, so output does not vary by
        /// machine or checkout path.</param>
        /// <param name="className">The generated partial class name, conventionally the
        /// UXML file name PascalCased.</param>
        /// <param name="namespaceName">The namespace the class is emitted into.</param>
        /// <exception cref="UxmlCodegenException">Duplicate names, colliding property
        /// names, a name yielding no identifier, or a property colliding with
        /// <paramref name="className"/>.</exception>
        public static string Generate(string uxmlText, string sourceFileName, string className, string namespaceName)
        {
            var document = new XmlDocument();
            document.LoadXml(uxmlText);

            var bindings = CollectBindings(document, className);

            var builder = new StringBuilder();
            builder.Append("// <auto-generated/> — generated from ").Append(sourceFileName)
                .Append(" by Cuvara.UIToolkit codegen. Do not edit.\n");
            builder.Append("namespace ").Append(namespaceName).Append("\n{\n");
            builder.Append("    using UnityEngine.UIElements;\n");
            builder.Append("    using Cuvara.UIToolkit.Utilities;\n\n");
            builder.Append("    public partial class ").Append(className).Append("\n    {\n");

            foreach (var binding in bindings)
            {
                if (binding.OriginalTag != null)
                {
                    builder.Append("        // Custom tag <").Append(binding.OriginalTag)
                        .Append("> — no known typed mapping, bound as ").Append(FallbackType).Append(".\n");
                }

                builder.Append("        public ").Append(binding.TypeName).Append(' ')
                    .Append(binding.PropertyName).Append(" { get; private set; }\n\n");
            }

            builder.Append("        public void AssignQueries(VisualElement root)\n        {\n");
            foreach (var binding in bindings)
            {
                builder.Append("            this.").Append(binding.PropertyName)
                    .Append(" = root.Require<").Append(binding.TypeName).Append(">(\"")
                    .Append(binding.UxmlName).Append("\");\n");
            }

            builder.Append("        }\n    }\n}\n");
            return builder.ToString();
        }

        private static List<Binding> CollectBindings(XmlDocument document, string className)
        {
            var bindings = new List<Binding>();
            var uxmlNameByProperty = new Dictionary<string, string>();
            var seenUxmlNames = new HashSet<string>();
            var duplicateUxmlNames = new List<string>();
            var errors = new List<string>();

            Visit(document.DocumentElement);

            if (duplicateUxmlNames.Count > 0)
            {
                errors.Insert(0, $"duplicate name attribute(s): {string.Join(", ", duplicateUxmlNames)} — every bound name must be unique within one UXML document");
            }

            if (errors.Count > 0)
            {
                throw new UxmlCodegenException("UXML codegen failed: " + string.Join("; ", errors) + ".");
            }

            return bindings;

            void Visit(XmlElement element)
            {
                if (element == null) return;
                if (!IsSkipped(element))
                {
                    var uxmlName = element.GetAttribute("name");
                    if (!string.IsNullOrEmpty(uxmlName)) Bind(element, uxmlName);
                }

                foreach (XmlNode child in element.ChildNodes)
                {
                    if (child is XmlElement childElement) Visit(childElement);
                }
            }

            void Bind(XmlElement element, string uxmlName)
            {
                if (!seenUxmlNames.Add(uxmlName))
                {
                    if (!duplicateUxmlNames.Contains(uxmlName)) duplicateUxmlNames.Add(uxmlName);
                    return;
                }

                var propertyName = UxmlIdentifier.ToPascalCase(uxmlName);
                if (propertyName.Length == 0)
                {
                    errors.Add($"name '{uxmlName}' yields no C# identifier");
                    return;
                }

                if (propertyName == className)
                {
                    errors.Add($"name '{uxmlName}' maps to property '{propertyName}', which collides with the class name — rename the element (e.g. suffix '-root')");
                    return;
                }

                if (uxmlNameByProperty.TryGetValue(propertyName, out var priorUxmlName))
                {
                    errors.Add($"names '{priorUxmlName}' and '{uxmlName}' both map to property '{propertyName}'");
                    return;
                }

                uxmlNameByProperty.Add(propertyName, uxmlName);
                bindings.Add(new Binding
                {
                    UxmlName = uxmlName,
                    PropertyName = propertyName,
                    TypeName = ResolveType(element, out var originalTag),
                    OriginalTag = originalTag,
                });
            }
        }

        private static bool IsSkipped(XmlElement element)
        {
            // Template and Style carry a name/src that references an asset, not an element
            // present in the cloned tree — querying for them would always fail.
            return element.LocalName == "Template" || element.LocalName == "Style";
        }

        private static string ResolveType(XmlElement element, out string originalTag)
        {
            if (element.NamespaceURI == UnityElementsNamespace)
            {
                // <ui:Instance template="..."/> clones into a TemplateContainer.
                if (element.LocalName == "Instance")
                {
                    originalTag = null;
                    return "TemplateContainer";
                }

                if (KnownElementTypes.Contains(element.LocalName))
                {
                    originalTag = null;
                    return element.LocalName;
                }
            }

            originalTag = element.Name;
            return FallbackType;
        }

        private sealed class Binding
        {
            public string UxmlName;
            public string PropertyName;
            public string TypeName;

            /// <summary>Non-null only for a fallback binding; the tag as written.</summary>
            public string OriginalTag;
        }
    }
}
