namespace Cuvara.UIToolkit.Editor.Tests
{
    using Cuvara.UIToolkit.Codegen;
    using NUnit.Framework;

    /// <summary>
    /// The generator core is a pure string→string function, so it is tested with string
    /// fixtures and no assets. These same tests compile and run under plain
    /// <c>dotnet</c> (the core has no Unity dependency — that IS one of the assertions
    /// here, enforced by the drift CLI compiling the same sources).
    /// </summary>
    public class UxmlBindingGeneratorTests
    {
        private const string ConfirmPopupUxml = @"<?xml version=""1.0"" encoding=""utf-8""?>
<ui:UXML xmlns:ui=""UnityEngine.UIElements"" editor-extension-mode=""False"">
    <ui:VisualElement name=""popup-root"">
        <ui:Label name=""popup-title"" text=""Title"" />
        <ui:Label name=""popup-body"" text=""Body"" />
        <ui:VisualElement name=""button-row"">
            <ui:Button name=""btn-ok"" text=""OK"" />
            <ui:Button name=""btn-cancel"" text=""Cancel"" />
        </ui:VisualElement>
    </ui:VisualElement>
</ui:UXML>";

        private static string Generate(string uxml, string className = "ConfirmPopup")
        {
            return UxmlBindingGenerator.Generate(uxml, className + ".uxml", className, "Game.UI");
        }

        [Test]
        public void KnownTags_EmitTypedProperties()
        {
            var source = Generate(ConfirmPopupUxml);

            Assert.That(source, Does.Contain("public VisualElement PopupRoot { get; private set; }"));
            Assert.That(source, Does.Contain("public Label PopupTitle { get; private set; }"));
            Assert.That(source, Does.Contain("public Label PopupBody { get; private set; }"));
            Assert.That(source, Does.Contain("public Button BtnOk { get; private set; }"));
            Assert.That(source, Does.Contain("public Button BtnCancel { get; private set; }"));
        }

        [Test]
        public void AssignQueries_ResolvesEveryNameThroughRequire()
        {
            var source = Generate(ConfirmPopupUxml);

            Assert.That(source, Does.Contain("public void AssignQueries(VisualElement root)"));
            Assert.That(source, Does.Contain("this.PopupTitle = root.Require<Label>(\"popup-title\");"));
            Assert.That(source, Does.Contain("this.BtnOk = root.Require<Button>(\"btn-ok\");"));
            Assert.That(source, Does.Contain("this.BtnCancel = root.Require<Button>(\"btn-cancel\");"));
        }

        [Test]
        public void ClassShape_IsPartial_InTheGivenNamespace_WithTheHeader()
        {
            var source = Generate(ConfirmPopupUxml);

            Assert.That(source, Does.StartWith(
                "// <auto-generated/> — generated from ConfirmPopup.uxml by Cuvara.UIToolkit codegen. Do not edit.\n"));
            Assert.That(source, Does.Contain("namespace Game.UI"));
            Assert.That(source, Does.Contain("public partial class ConfirmPopup"));
            Assert.That(source, Does.Not.Contain(" : "), "the class must not carry a base type — it composes via partial");
        }

        [Test]
        public void AnUnknownTag_FallsBackToVisualElement_NamingTheOriginalTag()
        {
            const string uxml = @"<ui:UXML xmlns:ui=""UnityEngine.UIElements"" xmlns:game=""Game.Widgets"">
    <game:MiniMap name=""mini-map"" />
</ui:UXML>";

            var source = Generate(uxml, "Hud");

            Assert.That(source, Does.Contain("public VisualElement MiniMap { get; private set; }"));
            Assert.That(source, Does.Contain("game:MiniMap"), "the comment must name the original tag");
            Assert.That(source, Does.Contain("this.MiniMap = root.Require<VisualElement>(\"mini-map\");"));
        }

        [Test]
        public void ATemplateDeclaration_IsNotBound()
        {
            // <ui:Template name=...> declares an asset reference; only <ui:Instance>
            // produces an element in the cloned tree.
            const string uxml = @"<ui:UXML xmlns:ui=""UnityEngine.UIElements"">
    <ui:Template name=""row-template"" src=""Row.uxml"" />
    <ui:Instance template=""row-template"" name=""first-row"" />
</ui:UXML>";

            var source = Generate(uxml, "ListScreen");

            Assert.That(source, Does.Not.Contain("RowTemplate"));
            Assert.That(source, Does.Contain("public TemplateContainer FirstRow { get; private set; }"));
        }

        [Test]
        public void UnnamedElements_AreSkipped()
        {
            const string uxml = @"<ui:UXML xmlns:ui=""UnityEngine.UIElements"">
    <ui:VisualElement>
        <ui:Label name=""only-me"" />
    </ui:VisualElement>
</ui:UXML>";

            var source = Generate(uxml, "View");

            Assert.That(source, Does.Contain("OnlyMe"));
            Assert.That(source.Split(new[] { "{ get; private set; }" }, System.StringSplitOptions.None).Length - 1,
                Is.EqualTo(1), "exactly one property");
        }

        [Test]
        public void DuplicateNames_Fail_ListingTheDuplicates()
        {
            const string uxml = @"<ui:UXML xmlns:ui=""UnityEngine.UIElements"">
    <ui:Label name=""popup-title"" />
    <ui:Label name=""popup-title"" />
    <ui:Button name=""btn-ok"" />
    <ui:Button name=""btn-ok"" />
</ui:UXML>";

            var exception = Assert.Throws<UxmlCodegenException>(() => Generate(uxml));

            Assert.That(exception.Message, Does.Contain("duplicate"));
            Assert.That(exception.Message, Does.Contain("popup-title"));
            Assert.That(exception.Message, Does.Contain("btn-ok"));
        }

        [Test]
        public void NamesCollidingAfterPascalCase_Fail_NamingBothForms()
        {
            const string uxml = @"<ui:UXML xmlns:ui=""UnityEngine.UIElements"">
    <ui:Label name=""popup-title"" />
    <ui:Label name=""popupTitle"" />
</ui:UXML>";

            var exception = Assert.Throws<UxmlCodegenException>(() => Generate(uxml));

            Assert.That(exception.Message, Does.Contain("popup-title"));
            Assert.That(exception.Message, Does.Contain("popupTitle"));
            Assert.That(exception.Message, Does.Contain("PopupTitle"));
        }

        [Test]
        public void ANameCollidingWithTheClassName_Fails()
        {
            // C# forbids a member named like its enclosing type, so this cannot be
            // emitted and must fail at generation time with a rename hint.
            const string uxml = @"<ui:UXML xmlns:ui=""UnityEngine.UIElements"">
    <ui:VisualElement name=""confirm-popup"" />
</ui:UXML>";

            var exception = Assert.Throws<UxmlCodegenException>(() => Generate(uxml));

            Assert.That(exception.Message, Does.Contain("confirm-popup"));
            Assert.That(exception.Message, Does.Contain("class name"));
        }

        [Test]
        public void KebabToPascal_EdgeCases()
        {
            Assert.That(UxmlIdentifier.ToPascalCase("popup-title"), Is.EqualTo("PopupTitle"));
            Assert.That(UxmlIdentifier.ToPascalCase("slot-2"), Is.EqualTo("Slot2"), "digits are kept");
            Assert.That(UxmlIdentifier.ToPascalCase("a--b"), Is.EqualTo("AB"), "consecutive dashes collapse");
            Assert.That(UxmlIdentifier.ToPascalCase("-leading"), Is.EqualTo("Leading"), "leading dash is dropped");
            Assert.That(UxmlIdentifier.ToPascalCase("trailing-"), Is.EqualTo("Trailing"));
            Assert.That(UxmlIdentifier.ToPascalCase("2nd-row"), Is.EqualTo("_2ndRow"), "digit-first gets an underscore");
            Assert.That(UxmlIdentifier.ToPascalCase("hp_bar.fill"), Is.EqualTo("HpBarFill"), "any non-alphanumeric separates");
            Assert.That(UxmlIdentifier.ToPascalCase("---"), Is.EqualTo(string.Empty), "no identifier at all");
        }

        [Test]
        public void GeneratingTwice_IsByteIdentical()
        {
            Assert.That(Generate(ConfirmPopupUxml), Is.EqualTo(Generate(ConfirmPopupUxml)));
        }

        [Test]
        public void EmissionOrder_IsDocumentOrder()
        {
            var source = Generate(ConfirmPopupUxml);

            var title = source.IndexOf("PopupTitle { get", System.StringComparison.Ordinal);
            var body = source.IndexOf("PopupBody { get", System.StringComparison.Ordinal);
            var ok = source.IndexOf("BtnOk { get", System.StringComparison.Ordinal);
            var cancel = source.IndexOf("BtnCancel { get", System.StringComparison.Ordinal);

            Assert.That(title, Is.LessThan(body));
            Assert.That(body, Is.LessThan(ok));
            Assert.That(ok, Is.LessThan(cancel));
        }
    }
}
